#!/usr/bin/env bash
read -ep "What is the depature place? " depvar
read -ep "What is the destination place? " desvar
read -ep "What file do you want to look in? " -i "Tourdetails.txt" filevar
awk -v dep="$depvar" '$2 == dep' Tourdetails.txt | awk -v des="$desvar" '$3 == des' | awk '{print $1 "\t" $2 "\t" $3 "\t" $4}'
